name: alpine-tools

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  call-parse-version-from-pom:
    uses: b521f771d8991e6f1d8e65ae05a8d783/base-tools/.github/workflows/ci.yml@main
    with:
      image_name: "alpine-tools"
