name: Build Windows Image

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: windows-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4.2.2

      - name: Build and push
        shell: powershell
        run: |
          docker build . -f ../../windows-tools.dockerfile
